plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android' version '1.9.22'
}

group = "com.builttoroam.devicecalendar"
version = "1.0-SNAPSHOT"

android {
    namespace "com.builttoroam.devicecalendar"

    compileSdk = 35

    defaultConfig {
        minSdk = 23
        targetSdk = 35
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "proguard-rules.pro"
    }

    sourceSets {
        main.java.srcDirs += "src/main/kotlin"
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = "17"
    }

    lint {
        disable 'InvalidPackage'
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.9.22"
    implementation "com.google.code.gson:gson:2.10.1"
    api "androidx.appcompat:appcompat:1.6.1"
    implementation "org.dmfs:lib-recur:0.12.2"
    implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
}
